### ISSUE TITLE
Can't install with VS2015

### ISSUE THREAD

**Issue by MartinL0815** [onolox/SmartSemicolon#2]
I can't install the extension using the downloadable VSIX file.

Here a screenshot of the error message:

> 
![Error Message in VSIX installer](https://user-images.githubusercontent.com/525700/37768787-bb4f8208-2dc6-11e8-9734-8046d234b4ae.png)

Here the installer log:

> [VSIXInstaller_173080e4-69ee-4e97-aa93-0c5e54eb8663.log](https://github.com/onolox/SmartSemicolon/files/1837332/VSIXInstaller_173080e4-69ee-4e97-aa93-0c5e54eb8663.log)

Installed on my system are VS2013 and VS2015:

> 
![About Microsoft Visual Studio 2015](https://user-images.githubusercontent.com/525700/37768934-409dd00e-2dc7-11e8-90e4-b34c8bafcd93.png)

**Comment by RoDo777** [comment]
I have the same problem.
I'm sure  it is because Version : **[15.0] does NOT mean VS 2015, it is VS 2017!**



Supported Products : Microsoft.VisualStudio.Community Version : [15.0]

So first, it is not supposed for Professional, Premium or Enterprise, AND
what is most important, **it is only for VS 2017 Community Version**

**Comment by onolox** [comment]
I've made this for my use, I can install it in enterprise edition.
But I will check this issue to make it more compatible.
